language: python
python:
    - 3.5
    - 3.6
before_install:
    - "pip install -U pip"
    - "python setup.py install"
script: 
    - "python3 -m unittest"
#    - "nosetests --with-coverage --cover-package"